### ISSUE TITLE
UDP plugin causes performance problems with OpenCPN

### ISSUE THREAD

**Issue by andyrbarrow** [tkurki/udp-nmea-plugin#9]
I was having problems with OpenCPN starting very slowly, freezing, and not shutting down without killing the process.

Am using OpenCPN with a SignalK connection, and was trying to use the UDP plugin for wireless connection to a tablet. When I enable the plugin and the SignalK server connection (all on RPI 4 / 4GB) OpenCPN is slow to respond, and will not close without killing the process. When I disable the connection in the server (not the plugin), OpenCPN will close properly and performance is acceptable. I do not have a UDP connection configured on OpenCPN.

I am noticing that keys/second on the UDP connection is very high - with no filtering on the connection, the connection speed is 400-500, and represents 98% of the total key's per second. If I filter some NMEA strings, I can get the keys/second down to around 250.

**Comment by tkurki** [comment]
`keys/second on the UDP connection ` - what are you referring to, as this plugin does not provide any stats.

**Comment by tkurki** [comment]
I suspect you are mixing up this plugin (udp output for nmea0183 data) and your server's udp input connection, so this issue is not really about this plugin.

And Slack is much more effective in this kind of troubleshooting.

**Comment by tkurki** [comment]
CLosing as stale.
